"use client";

import { useState } from "react";
import { FiAlignCenter, FiAlignJustify, FiAlignLeft, FiAlignRight, FiRefreshCw, FiSave, FiSquare } from "react-icons/fi";
import { ColorTarget, VisualGroup, fonts, numberValue, selectorGroups, useVisualStylesPanel, withPx } from "@/hooks/useVisualStylesPanel";
import { StyleObject } from "@/types/resume/ResumeStyle";

const cardClass = "rounded-2xl border border-slate-200 bg-white p-5 shadow-sm";
const titleClass = "mb-4 flex items-center justify-between text-base font-bold text-slate-900";
type PanelTab = "global" | "elements" | "selectors";

function MiniButton({ active, children, onClick }: { active?: boolean; children: React.ReactNode; onClick: () => void }) {
  return <button type="button" onClick={onClick} className={`min-h-11 flex-1 rounded-xl border px-3 py-2 text-sm font-semibold transition ${active ? "border-blue-500 bg-blue-50 text-blue-700 shadow-sm" : "border-slate-200 bg-white text-slate-700 hover:border-slate-300 hover:bg-slate-50"}`}>{children}</button>;
}

function Slider({ label, value, min, max, onChange, preview }: { label: string; value: number; min: number; max: number; onChange: (value: number) => void; preview?: React.ReactNode }) {
  return <label className="block rounded-xl bg-slate-50 p-3 text-sm font-semibold text-slate-700"><span className="flex items-center justify-between"><span>{label}</span>{preview}</span><input type="range" min={min} max={max} value={value} onChange={(event) => onChange(Number(event.target.value))} className="mt-3 w-full accent-blue-600" /></label>;
}

function TextInput({ label, value, onChange, placeholder }: { label: string; value?: string | number; onChange: (value: string) => void; placeholder?: string }) {
  return <label className="block rounded-xl bg-slate-50 p-3 text-sm font-semibold text-slate-700"><span>{label}</span><input value={String(value ?? "")} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-3 py-2 font-mono text-sm text-slate-900 outline-none focus:border-blue-500" /></label>;
}

function ColorControl({ label, target, colors }: { label: string; target: ColorTarget; colors: Pick<ReturnType<typeof useVisualStylesPanel>, "setColor" | "valueFor"> }) {
  const current = colors.valueFor(target);
  const pickerValue = /^#[0-9a-fA-F]{6}$/.test(current) ? current : "#000000";
  return <div className="rounded-xl bg-slate-50 p-3"><div className="mb-2 flex items-center justify-between"><span className="text-sm font-semibold text-slate-700">{label}</span><span className="h-7 w-12 rounded-lg border border-slate-200" style={{ backgroundColor: current }} /></div><div className="grid grid-cols-[56px_1fr] gap-2"><input type="color" value={pickerValue} onChange={(event) => colors.setColor(target, event.target.value)} className="h-10 w-14 cursor-pointer rounded-lg border border-slate-200 bg-white" /><input value={current} onChange={(event) => colors.setColor(target, event.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 font-mono text-sm text-slate-900 outline-none focus:border-blue-500" /></div></div>;
}

function Alignment({ active, onChange }: { active?: string | number; onChange: (patch: StyleObject) => void }) {
  return <div className="grid grid-cols-4 gap-2"><MiniButton active={active === "left"} onClick={() => onChange({ textAlign: "left" })}><FiAlignLeft className="mx-auto" /></MiniButton><MiniButton active={active === "center"} onClick={() => onChange({ textAlign: "center" })}><FiAlignCenter className="mx-auto" /></MiniButton><MiniButton active={active === "right"} onClick={() => onChange({ textAlign: "right" })}><FiAlignRight className="mx-auto" /></MiniButton><MiniButton active={active === "justify"} onClick={() => onChange({ textAlign: "justify" })}><FiAlignJustify className="mx-auto" /></MiniButton></div>;
}

export default function StylesPanel() {
  const controls = useVisualStylesPanel();
  const { style, selectedNode, selectedGroup, updateGlobal, updateSelector, updateElement, resetStyles, applyStyles } = controls;
  const [tab, setTab] = useState<PanelTab>("global");
  const [selector, setSelector] = useState<VisualGroup | "section" | "text" | "link" | "listItem">("section");
  const selectedPatch = style.elements?.[selectedNode?.id ?? ""] ?? {};

  const renderSmartControls = (scope: "selector" | "element", target: string, current: StyleObject, update: (patch: StyleObject) => void, group: string = selectedGroup) => <div className="space-y-3">
    {(group === "heading" || group === "paragraph" || group === "text" || group === "link") && <><ColorControl colors={controls} label="Text color" target={{ scope, target, key: "color", label: "Text color" }} /><div className="grid grid-cols-2 gap-2">{fonts.map((font) => <MiniButton key={font.id} active={current.fontFamily === font.value} onClick={() => update({ fontFamily: font.value })}><span style={{ fontFamily: font.value }}>Aa {font.name}</span></MiniButton>)}</div><Slider label="Size" min={10} max={38} value={numberValue(current.fontSize, group === "heading" ? 22 : 14)} onChange={(value) => update({ fontSize: withPx(value) })} preview={<span style={{ fontSize: numberValue(current.fontSize, 16) }}>Aa</span>} /><div className="grid grid-cols-3 gap-2"><MiniButton active={current.fontWeight === 300} onClick={() => update({ fontWeight: 300 })}>Light</MiniButton><MiniButton active={current.fontWeight === 400} onClick={() => update({ fontWeight: 400 })}>Normal</MiniButton><MiniButton active={current.fontWeight === 700} onClick={() => update({ fontWeight: 700 })}>Bold</MiniButton></div><Alignment active={current.textAlign} onChange={update} /><Slider label="Line spacing" min={10} max={24} value={numberValue(current.lineHeight, 1.5) * 10} onChange={(value) => update({ lineHeight: value / 10 })} /></>}
    {group === "image" && <><Slider label="Width" min={48} max={260} value={numberValue(current.width, 96)} onChange={(value) => update({ width: withPx(value) })} /><Slider label="Height" min={48} max={260} value={numberValue(current.height, 96)} onChange={(value) => update({ height: withPx(value) })} /><Slider label="Rounded corners" min={0} max={120} value={numberValue(current.borderRadius, 0)} onChange={(value) => update({ borderRadius: withPx(value) })} /><div className="grid grid-cols-3 gap-2"><MiniButton onClick={() => update({ objectFit: "cover" })}>Fill frame</MiniButton><MiniButton onClick={() => update({ objectFit: "contain" })}>Fit inside</MiniButton><MiniButton onClick={() => update({ objectFit: "fill" })}>Stretch</MiniButton></div></>}
    {group === "icon" && <><Slider label="Icon size" min={12} max={64} value={numberValue(current.fontSize, 20)} onChange={(value) => update({ fontSize: withPx(value) })} /><ColorControl colors={controls} label="Icon color" target={{ scope, target, key: "color", label: "Icon color" }} /><ColorControl colors={controls} label="Icon background" target={{ scope, target, key: "backgroundColor", label: "Icon background" }} /><Slider label="Padding" min={0} max={24} value={numberValue(current.padding, 0)} onChange={(value) => update({ padding: withPx(value) })} /></>}
    {(group === "list" || group === "listItem") && <><div className="grid grid-cols-4 gap-2"><MiniButton onClick={() => update({ listStyleType: "disc" })}>•</MiniButton><MiniButton onClick={() => update({ listStyleType: "'✓ '" })}>✓</MiniButton><MiniButton onClick={() => update({ listStyleType: "'— '" })}>—</MiniButton><MiniButton onClick={() => update({ listStyleType: "none" })}>None</MiniButton></div><Slider label="Between items" min={0} max={32} value={numberValue(current.gap, 8)} onChange={(value) => update({ gap: withPx(value) })} /><ColorControl colors={controls} label="Text color" target={{ scope, target, key: "color", label: "Text color" }} /></>}
    {(group === "container" || group === "section") && <><div className="grid grid-cols-2 gap-2"><MiniButton onClick={() => update({ display: "flex", flexDirection: "column" })}>⬇ Vertical</MiniButton><MiniButton onClick={() => update({ display: "flex", flexDirection: "row" })}>➡ Horizontal</MiniButton></div><Slider label="Gap" min={0} max={40} value={numberValue(current.gap, 12)} onChange={(value) => update({ gap: withPx(value) })} /><Slider label="Padding" min={0} max={36} value={numberValue(current.padding, 12)} onChange={(value) => update({ padding: withPx(value) })} /><ColorControl colors={controls} label="Background" target={{ scope, target, key: "backgroundColor", label: "Background" }} /><Slider label="Rounded corners" min={0} max={32} value={numberValue(current.borderRadius, 0)} onChange={(value) => update({ borderRadius: withPx(value) })} /></>}
  </div>;

  return <div className="space-y-4"><div className={cardClass}><h3 className="text-xl font-black text-slate-950">Style Panel</h3><p className="mt-1 text-sm text-slate-500">Choose Global, Selectors, or Elements. Click any item on the canvas to make it active for element-level styling.</p><div className="mt-4 grid grid-cols-3 gap-2">{(["global", "elements", "selectors"] as PanelTab[]).map((item) => <MiniButton key={item} active={tab === item} onClick={() => setTab(item)}>{item}</MiniButton>)}</div></div>
    {tab === "global" && <div className={cardClass}><h4 className={titleClass}>Global resume container</h4><div className="space-y-3"><div className="grid grid-cols-2 gap-2">{fonts.map((font) => <MiniButton key={font.id} active={style.global?.fontFamily === font.value} onClick={() => updateGlobal({ fontFamily: font.value })}><span style={{ fontFamily: font.value }}>{font.name}</span></MiniButton>)}</div><Slider label="Font size" min={10} max={24} value={numberValue(style.global?.fontSize, 14)} onChange={(value) => updateGlobal({ fontSize: withPx(value) })} /><Slider label="Line height" min={10} max={24} value={numberValue(style.global?.lineHeight, 1.5) * 10} onChange={(value) => updateGlobal({ lineHeight: value / 10 })} /><ColorControl colors={controls} label="Text color" target={{ scope: "global", key: "color", label: "Global text color" }} /><ColorControl colors={controls} label="Background" target={{ scope: "global", key: "backgroundColor", label: "Global background" }} /><TextInput label="Padding" value={style.global?.padding ?? "40px"} onChange={(value) => updateGlobal({ padding: value })} /><TextInput label="Margin" value={style.global?.margin ?? "0 auto"} onChange={(value) => updateGlobal({ margin: value })} /><div className="rounded-xl border border-slate-200 p-3"><p className="mb-3 text-sm font-bold text-slate-700">Two-column layout</p><Slider label="Left column %" min={20} max={80} value={numberValue(style.global?.leftColumnWidth, 34)} onChange={(value) => updateGlobal({ leftColumnWidth: `${value}%` })} /><Slider label="Right column %" min={20} max={80} value={numberValue(style.global?.rightColumnWidth, 66)} onChange={(value) => updateGlobal({ rightColumnWidth: `${value}%` })} /><div className="mt-3 grid grid-cols-2 gap-3"><ColorControl colors={controls} label="Left color" target={{ scope: "global", key: "sidebarBackgroundColor", label: "Left column color" }} /><ColorControl colors={controls} label="Right color" target={{ scope: "global", key: "mainBackgroundColor", label: "Right column color" }} /></div><TextInput label="Vertical border" value={style.global?.columnBorder ?? "1px solid #e5e7eb"} onChange={(value) => updateGlobal({ columnBorder: value })} placeholder="1px solid #e5e7eb" /></div></div></div>}
    {tab === "selectors" && <div className={cardClass}><h4 className={titleClass}>Selectors</h4><div className="mb-4 grid grid-cols-2 gap-2">{selectorGroups.map((item) => <MiniButton key={item} active={selector === item} onClick={() => setSelector(item)}>{item}</MiniButton>)}</div>{renderSmartControls("selector", selector, style.selectors?.[selector] ?? {}, (patch) => updateSelector(selector, patch), selector)}</div>}
    {tab === "elements" && <div className={cardClass}><h4 className={titleClass}>Active element</h4><p className="mb-4 text-sm text-slate-500">{selectedNode ? `${selectedNode.name} (${selectedGroup})` : "Click any element in the canvas first."}</p>{selectedNode ? renderSmartControls("element", selectedNode.id, selectedPatch, updateElement, selectedGroup) : <div className="rounded-xl border border-dashed border-slate-300 p-5 text-center text-sm text-slate-400"><FiSquare className="mx-auto mb-2" />No active element</div>}</div>}
    <div className="sticky bottom-3 rounded-2xl border border-slate-200 bg-white/95 p-3 shadow-lg backdrop-blur"><div className="flex gap-3"><button onClick={resetStyles} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-slate-100 px-4 py-3 font-bold text-slate-700 hover:bg-slate-200"><FiRefreshCw />Reset</button><button onClick={applyStyles} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-3 font-bold text-white hover:bg-blue-700"><FiSave />Apply</button></div></div></div>;
}
